version: "3.7"

services:
  webserver:
    container_name: wp-search
    build: ./
    ports:
      - 3030:3030
    volumes:
      - type: bind
        source: .
        target: /app
    networks:
      - fronend

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.1
    environment:
      - discovery.type=single-node
      - cluster.name=docker-
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch-data:/usr/share/elasticsearch/data/
    networks:
      - fronend

networks:
  fronend:
  backend:
    internal: true
