version: "3.7"

services:
  webserver:
    build: ./
    ports:
      - 3030:3030
    volumes:
      - type: bind
        source: .
        target: /app
    working_dir: /app

  redis:
    image: redis:alpine

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
